export const FETCH_USER         = 'FETCH_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const CITY_NAME_INPUT_CHANGE = 'CITY_NAME_INPUT_CHANGE';

export const FETCH_GEOLOCATION = 'FETCH_GEOLOCATION';
export const FETCH_GEOLOCATION_SUCCESS = 'FETCH_GEOLOCATION_SUCCESS';
export const FETCH_NEARBY_CONTRACTORS = 'FETCH_NEARBY_CONTRACTORS';
export const FETCH_NEARBY_ERROR = 'FETCH_NEARBY_ERROR';
