export const FETCH_USER         = 'FETCH_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const CITY_NAME_INPUT_CHANGE = 'CITY_NAME_INPUT_CHANGE';
export const FETCH_CONTRACTORS = 'FETCH_CONTRACTORS';

export const FETCH_GEOLOCATION = 'FETCH_GEOLOCATION';
export const FETCH_GEOLOCATION_SUCCESS = 'FETCH_GEOLOCATION_SUCCESS';
