export const FETCH_USER         = 'FETCH_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const FETCH_GEOLOCATION = 'FETCH_GEOLOCATION';
export const FETCH_GEOLOCATION_SUCCESS = 'FETCH_GEOLOCATION_SUCCESS';
export const FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION';

export const UPDATE_SOCKET_ID = 'UPDATE_SOCKET_ID';
export const FETCH_SOCKET_ID = 'FETCH_SOCKET_ID'
export const FETCH_NEARBY_STRETCHOLOGISTS = 'FETCH_NEARBY_STRETCHOLOGISTS';

export const FETCH_NEARBY_REQUESTS = 'FETCH_NEARBY_REQUESTS';
export const FETCH_NEARBY_NOTIFICATION = 'FETCH_NEARBY_NOTIFICATION';
export const NEARBY_REQUESTS_FAIL = 'FETCH_NEARBY_REQUESTS';

export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const CREATE_BOOKING = 'CREATE_BOOKING';
